---
# Items que aplican para todos los perfiles:
eureka:
  client:
    serviceUrl:      
      defaultZone: http://eureka:password@localhost:8010/eureka/,http://localhost:8011/eureka/,http://localhost:8012/eureka/

---
spring:
  profiles: persona
words: Jose, Carlos
  
---
spring:
  profiles: direccion
words: Panecillo, Calzado
